const images = import.meta.glob('../assets/shoes/**/**.jpg', { eager: true });
const imagesJpeg = import.meta.glob('../assets/shoes/**/**.jpeg', { eager: true });
const imagesPng = import.meta.glob('../assets/shoes/**/**.png', { eager: true });

const data = [
  {
    id: 1,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: images['../assets/shoes/Nike/running/men/nature-running-shoes.jpg'].default,
    title: "Nike nuture running shoe",
    color: ["black", "red"],
    size: [39, 40, 41, 42, 43],
    rate: 5,
    itemsNumber: 5,
    price: 750,
    discount: 10,
  },
  {
    id: 2,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: images["../assets/shoes/Nike/running/men/nk-run-swift.jpg"].default,
    title: "Nike run swift shoe",
    color: ["white", "gray"],
    size: [39, 40, 41],
    rate: 5,
    itemsNumber: 2,
    price: 1000,
    discount: 15,
  },
  {
    id: 3,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: images["../assets/shoes/Nike/running/men/running-revolution.jpg"].default,
    title: "Nike running revolution shoe",
    color: ["white", "gray", "black"],
    size: [40, 41, 42, 43],
    rate: 5,
    itemsNumber: 10,
    price: 600,
    discount: 20,
  },
  {
    id: 4,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: images["../assets/shoes/Nike/running/men/running-shoe1.jpg"].default,
    title: "Nike running shoe",
    color: ["gray", "black"],
    size: [40, 41, 42, 43],
    rate: 5,
    itemsNumber: 10,
    price: 600,
    discount: 20,
  },
  {
    id: 5,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: imagesPng["../assets/shoes/Nike/running/men/run-swift.png"].default,
    title: "Nike running swift shoe",
    color: ["orange", "gray", "black"],
    size: [40, 42, 43],
    rate: 5,
    itemsNumber: 6,
    price: 699,
    discount: 15,
  },
  {
    id: 6,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: images["../assets/shoes/Nike/running/women/running-shoe1.jpg"].default,
    title: "Nike running shoe for women",
    color: ["white", "red", "black"],
    size: [39, 40, 41],
    rate: 5,
    itemsNumber: 3,
    price: 500,
    discount: 0,
  },
  {
    id: 7,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: images["../assets/shoes/Nike/running/women/running-shoe2.jpg"].default,
    title: "Nike running shoe",
    color: ["gray", "white", "black"],
    size: [39, 40, 41, 42, 43],
    rate: 5,
    itemsNumber: 7,
    price: 480,
    discount: 5,
  },
  {
    id: 8,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: images["../assets/shoes/Nike/running/women/running-shoe3.jpg"].default,
    title: "Nike running shoe",
    color: ["ping", "red", "white"],
    size: [39, 40, 41, 42],
    rate: 5,
    itemsNumber: 9,
    price: 760,
    discount: 12,
  },
  {
    id: 9,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: images["../assets/shoes/Nike/running/women/running-shoe4.jpg"].default,
    title: "Nike running swift shoe",
    color: ["ping", "red", "white"],
    size: [39, 40, 41, 42],
    rate: 5,
    itemsNumber: 9,
    price: 760,
    discount: 12,
  },
  {
    id: 10,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: images["../assets/shoes/Nike/running/women/running-shoe5.jpg"].default,
    title: "Nike running swift shoe",
    color: ["ping", "red", "white"],
    size: [39, 40, 41],
    rate: 5,
    itemsNumber: 6,
    price: 760,
    discount: 15,
  },
  {
    id: 11,
    company: "Nike",
    category: "sneakers",
    gender: ["men"],
    img: images["../assets/shoes/Nike/sneakers/men/jordan1.jpg"].default,
    title: "Nike Air Jordan",
    color: ["brown", "beige", "white"],
    size: [38, 39, 40, 41, 42, 43],
    rate: 5,
    itemsNumber: 10,
    price: 200,
    discount: 10,
  },
  {
    id: 12,
    company: "Nike",
    category: "sneakers",
    gender: ["men"],
    img: imagesJpeg["../assets/shoes/Nike/sneakers/men/jordan2.jpeg"].default,
    title: "Nike Air Jordan Mid",
    color: ["blue", "white", "red", "gold"],
    size: [38, 39, 40, 41, 42, 43, 44],
    rate: 5,
    itemsNumber: 20,
    price: 220,
    discount: 12,
  },
  {
    id: 13,
    company: "Nike",
    category: "sneakers",
    gender: ["men"],
    img: imagesJpeg["../assets/shoes/Nike/sneakers/men/airforce1.jpeg"].default,
    title: "Nike Air Force",
    color: ["black", "white", "grey"],
    size: [40, 41, 42, 43, 44, 45, 46],
    rate: 5,
    itemsNumber: 25,
    price: 180,
    discount: 8,
  },
  {
    id: 14,
    company: "Converse",
    category: "sneakers",
    gender: ["women"],
    img: images["../assets/shoes/Converse/women/sneakers1.jpg"].default,
    title: "Converse Chuck Taylor All Star",
    color: ["red", "white", "gold"],
    size: [36, 37, 38, 39, 40, 41, 42, 43],
    rate: 5,
    itemsNumber: 15,
    price: 150,
    discount: 5,
  },
  {
    id: 15,
    company: "Converse",
    category: "sneakers",
    gender: ["women"],
    img: imagesJpeg["../assets/shoes/Converse/women/pink_high_tops.jpeg"].default,
    title: "Converse Chuck Taylor All Star High Top",
    color: ["pink", "white"],
    size: [36, 37, 38, 39, 40, 41],
    rate: 5,
    itemsNumber: 12,
    price: 130,
    discount: 10,
  },
  {
    id: 15,
    company: "Converse",
    category: "sneakers",
    gender: ["women"],
    img: images["../assets/shoes/Converse/women/red-high-top.jpg"].default,
    title: "Converse High Top Red",
    color: ["red", "white"],
    size: [39, 40, 41, 42, 43],
    rate: 5,
    itemsNumber: 10,
    price: 60,
    discount: 10,
  },
  {
    id: 16,
    company: "Converse",
    category: "sneakers",
    gender: ["women", "men"],
    img: imagesJpeg["../assets/shoes/Converse/black-high-top.jpeg"].default,
    title: "Converse High Top Black",
    color: ["black", "white"],
    size: [39, 40, 41, 42, 43],
    rate: 5,
    itemsNumber: 8,
    price: 60,
    discount: 10,
  },
  {
    id: 17,
    company: "Nike",
    category: "sneakers",
    gender: ["men", "women"],
    img: imagesJpeg["../assets/shoes/Nike/sneakers/airforce2.jpeg"].default,
    title: "Nike Air Force Black",
    color: ["black"],
    size: [39, 40, 41, 42, 43, 44],
    rate: 5,
    itemsNumber: 12,
    price: 90,
    discount: 5,
  },
  {
    id: 18,
    company: "Nike",
    category: "sneakers",
    gender: ["women"],
    img: images["../assets/shoes/Nike/sneakers/women/sneaker1.jpg"].default,
    title: "Nike Court Vision Low",
    color: ["white", "pink"],
    size: [36, 37, 38, 39, 40],
    rate: 4,
    itemsNumber: 15,
    price: 75,
    discount: 10,
  },
  {
    id: 19,
    company: "Nike",
    category: "sneakers",
    gender: ["women"],
    img: images["../assets/shoes/Nike/sneakers/women/sneakers2.jpg"].default,
    title: "Nike Air Jordan Pink",
    color: ["pink"],
    size: [36, 37, 38, 39, 40],
    rate: 5,
    itemsNumber: 10,
    price: 100,
    discount: 15,
  },
  {
    id: 20,
    company: "Nike",
    category: "sneakers",
    gender: ["women"],
    img: images["../assets/shoes/Nike/sneakers/women/sneakers3.jpg"].default,
    title: "Nike Dunk Low Pink/White",
    color: ["pink", "white"],
    size: [36, 37, 38, 39, 40],
    rate: 4.8,
    itemsNumber: 8,
    price: 85,
    discount: 10,
  },
  {
    id: 21,
    company: "Converse",
    category: "sneakers",
    gender: ["women"],
    img: images["../assets/shoes/Converse/women/sneakers3.jpg"].default,
    title: "Converse High Top Celestial Pink/White",
    color: ["pink", "white", "yellow"],
    size: [36, 37, 38, 39, 40],
    rate: 5,
    itemsNumber: 12,
    price: 75,
    discount: 5,
  },
  {
    id: 22,
    company: "Converse",
    category: "sneakers",
    gender: ["women"],
    img: images["../assets/shoes/Converse/women/sneakers4.jpg"].default,
    title: "Converse High Top Lilac/White",
    color: ["lilac", "white", "yellow"],
    size: [36, 37, 38, 39, 40],
    rate: 4,
    itemsNumber: 15,
    price: 78,
    discount: 7,
  },
  {
    id: 23,
    company: "Converse",
    category: "sneakers",
    gender: ["women", "men"],
    img: images["../assets/shoes/Converse/sneakers1.jpg"].default,
    title: "Converse High Top White",
    color: ["black", "white"],
    size: [36, 37, 38, 39, 40],
    rate: 5,
    itemsNumber: 10,
    price: 80,
    discount: 10,
  },
  {
    id: 24,
    company: "Adidas",
    category: "sneakers",
    gender: ["women", "men"],
    img: images["../assets/shoes/Adidas/sneakers/sneakers1.jpg"].default,
    title: "Adidas Forum High Top",
    color: ["blue", "white"],
    size: [38, 39, 40, 41, 42],
    rate: 4.5,
    itemsNumber: 15,
    price: 120,
    discount: 15,
  },
  {
    id: 25,
    company: "Adidas",
    category: "sneakers",
    gender: ["women", "men"],
    img: images["../assets/shoes/Adidas/sneakers/sneakers2.jpg"].default,
    title: "Adidas Forum High Top Grey",
    color: ["grey", "white"],
    size: [38, 39, 40, 41, 42],
    rate: 4.7,
    itemsNumber: 20,
    price: 130,
    discount: 10,
  },
];

export default data;
