const data = [
  {
    id: 1,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: require("../assets/shoes/Nike/running/men/nature-running-shoes.jpg"),
    title: "Nike nuture running shoe",
    color: ["black", "red"],
    size: [39, 40, 41, 42, 43],
    itemsNumber: 5,
    price: 750,
    discount: 10,
  },
  {
    id: 2,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: require("../assets/shoes/Nike/running/men/nk-run-swift.jpg"),
    title: "Nike run swift shoe",
    color: ["white", "gray"],
    size: [39, 40, 41],
    itemsNumber: 2,
    price: 1000,
    discount: 15,
  },
  {
    id: 3,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: require("../assets/shoes/Nike/running/men/running-revolution.jpg"),
    title: "Nike running revolution shoe",
    color: ["white", "gray", "black"],
    size: [40, 41, 42, 43],
    itemsNumber: 10,
    price: 600,
    discount: 20,
  },
  {
    id: 4,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: require("../assets/shoes/Nike/running/men/running-shoe1.jpg"),
    title: "Nike running shoe",
    color: ["gray", "black"],
    size: [40, 41, 42, 43],
    itemsNumber: 10,
    price: 600,
    discount: 20,
  },
  {
    id: 5,
    company: "Nike",
    catigory: "running",
    gender: ["men"],
    img: require("../assets/shoes/Nike/running/men/run-swift.png"),
    title: "Nike running swift shoe",
    color: ["orange", "gray", "black"],
    size: [40, 42, 43],
    itemsNumber: 6,
    price: 699,
    discount: 15,
  },
  {
    id: 6,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: require("../assets/shoes/Nike/running/women/running-shoe1.jpg"),
    title: "Nike running shoe for women",
    color: ["white", "red", "black"],
    size: [39, 40, 41],
    itemsNumber: 3,
    price: 500,
    discount: 0,
  },
  {
    id: 7,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: require("../assets/shoes/Nike/running/women/running-shoe2.jpg"),
    title: "Nike running shoe",
    color: ["gray", "white", "black"],
    size: [39, 40, 41, 42, 43],
    itemsNumber: 7,
    price: 480,
    discount: 5,
  },
  {
    id: 8,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: require("../assets/shoes/Nike/running/women/running-shoe3.jpg"),
    title: "Nike running shoe",
    color: ["ping", "red", "white"],
    size: [39, 40, 41, 42],
    itemsNumber: 9,
    price: 760,
    discount: 12,
  },
  {
    id: 9,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: require("../assets/shoes/Nike/running/women/running-shoe4.jpg"),
    title: "Nike running swift shoe",
    color: ["ping", "red", "white"],
    size: [39, 40, 41, 42],
    itemsNumber: 9,
    price: 760,
    discount: 12,
  },
  {
    id: 10,
    company: "Nike",
    catigory: "running",
    gender: ["women"],
    img: require("../assets/shoes/Nike/running/women/running-shoe5.jpg"),
    title: "Nike running swift shoe",
    color: ["ping", "red", "white"],
    size: [39, 40, 41],
    itemsNumber: 6,
    price: 760,
    discount: 15,
  },
];

export default data;
